[package]
name = "bort"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = { version = "0.13.2", default-features = false }
rustc-hash = "1.1.0"

[dev-dependencies]
criterion = "0.5.1"
fastrand = "1.9.0"  # For "fuzzing"
glam = "0.24.0"  # For doc-test

[[bench]]
name = "access"
harness = false

[profile.bench]
lto = "thin"
