[package]
name = "geode"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = "0.13.2"
rustc-hash = "1.1.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "access"
harness = false

[profile.bench]
lto = "thin"
