[package]
name = "mini-geode"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = "0.13.2"
rustc-hash = "1.1.0"

[dev-dependencies]
atomic_refcell = "0.1.9"
criterion = "0.4.0"
fastrand = "1.8.0"

[[bench]]
name = "cell"
harness = false

[profile.release]
lto = true
