[package]
name = "mini-geode"
version = "0.1.0"
edition = "2021"

[dependencies]
derive-where = "1.0.0"
fnv = "1.0.7"

[dev-dependencies]
atomic_refcell = "0.1.9"
criterion = "0.4.0"
fastrand = "1.8.0"

[[bench]]
name = "cell"
harness = false

[profile.release]
lto = true
