[package]
name = "bort"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = { version = "0.13.2", default-features = false }
rustc-hash = "1.1.0"

[dev-dependencies]
cgmath = "0.18.0"  # For doc-test
criterion = "0.4.0"

[[bench]]
name = "access"
harness = false

[profile.bench]
lto = "thin"
