[package]
name = "saddle"
version = "0.1.0"
edition = "2021"

[dependencies]
cfgenius = "0.1.0"
derive-where = "1.2.1"
linkme = "0.3.14"
partial-scope = { path = "../partial-scope" }
petgraph = "0.6.4"
rustc-hash = "1.1.0"

[features]
disable-static-validation = []
