[package]
name = "saddle"
version = "0.1.0"
edition = "2021"

[dependencies]
derive-where = "1.2.1"
linkme = "0.3.14"
partial-scope = { path = "../partial-scope" }
petgraph = "0.6.3"
rustc-hash = "1.1.0"
